TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
QMK_SETTINGS = yes
SPACE_CADET_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
SPLIT_KEYBOARD = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
