TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
QMK_SETTINGS = yes
SPACE_CADET_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = no
