name: Build my firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli@sha256:16c4916e95b99bf88d27b15aec8db409ee17265d1710287fde248c6666508966

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          git config --global --add safe.directory "$(pwd)"
          qmk compile -kb bastardkb/charybdis/3x5/v2/splinky_3 -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .build/*.uf2
